[PM-2066] Remove waste logging
input-output-hk/scalanet pull request #79
Opened 2020-05-27 07:21 UTC by KonradStaniec

2020-05-28 08:25 UTC, pslaski approved these changes

2020-05-28 16:25 UTC, ntallar requested changes
How much of an improvement is removing this logging? Maybe we should eventually remove more so as to continue improving it?

2020-05-28 16:25 UTC, ntallar commented on scalanet/src/io/iohk/scalanet/peergroup/dynamictls/DynamicTLSPeerGroupInternals.scala
> +              log.info("Decoded new message from peer {}", ctx.channel().remoteAddress())
Shouldn't this be on debug?

2020-05-28 16:25 UTC, ntallar commented on scalanet/src/io/iohk/scalanet/peergroup/dynamictls/DynamicTLSPeerGroupInternals.scala
> +            log.info("Unexpected decoding error {} from peer {}", value: Any, ctx.channel().remoteAddress(): Any)
Should this be an error msg?

2020-05-29 05:20 UTC, KonradStaniec commented
It is hard to quantify tbh, i am removing only this one as it was only one which popped out on profiler during sync, if there will any other after that then we can remove it as well

2020-05-29 15:41 UTC, ntallar requested changes

2020-05-29 15:41 UTC, ntallar commented on build.sc
> +  def publishVersion = "0.1.12-SNAPSHOT"
This should now be updated to 0.1.13-SNAPSHOT, right?

2020-05-29 15:55 UTC, ntallar approved these changes
LGTM!
```
     /(__M__)\
    /, ,   , ,\
   /' ' 'V' ' '\       ARV

------------------------------------------------
Thank you for visiting https://asciiart.website/
This ASCII pic can be found at
https://asciiart.website/index.php?art=animals/bats
```

2020-05-29 15:55 UTC, merged